import { SuiJsonRpcClient, getJsonRpcFullnodeUrl } from '@mysten/sui/jsonRpc'
import type Anthropic from '@anthropic-ai/sdk'
import { fetchPolicyState, validateAction, buildActionPtb } from 'actionflow'
import type { ScallopConfig } from 'actionflow'
import { createLocalSigner, submitTransaction } from 'agentrunner'
import type { RunActionResult, TransactionSigner } from 'agentrunner'
import { checkEligibility } from './decision.js'
import { consultDecisionAI } from './aiDecision.js'
import type { WalrusUploader } from './walrus.js'

export interface PolicyLoopOptions {
  policyId: string
  packageId: string
  walrusBlobId?: string
  walrus?: {
    uploader: WalrusUploader
    epochs?: number
    deletable?: boolean
  }
  scallop?: ScallopConfig
  suiClient?: SuiJsonRpcClient
  signer?: TransactionSigner
  ai?: {
    client: Anthropic
    marketContext?: string
    throwOnAiFailure?: boolean
  }
}

export type PolicyLoopResult =
  | { ok: true; status: 'skipped'; reason: string }
  | { ok: false; status: 'upload_failed'; reason: string }
  | RunActionResult

export async function runPolicyCycle(opts: PolicyLoopOptions): Promise<PolicyLoopResult> {
  const suiClient =
    opts.suiClient ?? new SuiJsonRpcClient({ url: getJsonRpcFullnodeUrl('testnet'), network: 'testnet' })
  const nowMs = Date.now()

  const state = await fetchPolicyState(opts.policyId, suiClient)

  const eligibility = checkEligibility(state, nowMs)
  if (!eligibility.eligible) {
    return { ok: true, status: 'skipped', reason: eligibility.reason }
  }

  let decision: { protocol: string; amount: number; action: 'supply' }
  let decisionReasoning: string | undefined

  if (opts.ai) {
    const aiDecision = await consultDecisionAI(state, opts.ai.client, {
      marketContext: opts.ai.marketContext,
      throwOnAiFailure: opts.ai.throwOnAiFailure,
    })
    if (aiDecision.kind === 'skip') {
      return { ok: true, status: 'skipped', reason: aiDecision.reason }
    }
    // action: 'supply' added here — not generated by Claude — so Claude cannot
    // accidentally emit an unsupported action type.
    decision = { protocol: aiDecision.protocol, amount: aiDecision.amount, action: 'supply' }
    decisionReasoning = aiDecision.reasoning
  } else {
    // Legacy mode: maintained solely for backward compatibility with existing callers
    // that have not configured an AI client. It is NOT used as a fallback after AI
    // failures — if opts.ai is provided but Claude fails, the cycle skips.
    decision = {
      protocol: state.allowedProtocols[0],
      amount: Math.min(state.maxTotalBudget - state.spentTotal, state.maxSingleTx),
      action: 'supply',
    }
  }

  const validated = validateAction(
    { protocol: decision.protocol, amount: decision.amount, action: decision.action },
    state,
    nowMs,
    opts.policyId,
  )
  if (!validated.ok) {
    return { ok: false, status: 'validation_failed', errors: validated.errors }
  }

  let walrusBlobId: string
  if (opts.walrus) {
    const artifact = {
      policyId: opts.policyId,
      protocol: decision.protocol,
      action: decision.action,
      amount: decision.amount,
      decisionSource: opts.ai ? 'ai' : 'legacy',
      marketContextPresent: Boolean(opts.ai?.marketContext),
      ...(decisionReasoning !== undefined ? { decisionReasoning } : {}),
      createdAt: new Date().toISOString(),
    }
    try {
      const result = await opts.walrus.uploader.uploadJson({
        data: artifact,
        epochs: opts.walrus.epochs,
        deletable: opts.walrus.deletable,
      })
      walrusBlobId = result.blobId
    } catch (err) {
      return {
        ok: false,
        status: 'upload_failed',
        reason: err instanceof Error ? err.message : String(err),
      }
    }
  } else {
    if (!opts.walrusBlobId) {
      return {
        ok: false,
        status: 'config_missing',
        reason: 'walrusBlobId required when walrus uploader is not configured',
      }
    }
    walrusBlobId = opts.walrusBlobId
  }

  const built = buildActionPtb(validated.action, walrusBlobId, opts.packageId, opts.scallop)
  if (!built.ok) {
    return built
  }

  const signer = opts.signer ?? createLocalSigner()
  built.tx.setSender(signer.toSuiAddress())

  return submitTransaction(built.tx, signer, suiClient)
}

export { checkEligibility } from './decision.js'
export type { EligibilityResult } from './decision.js'
export { consultDecisionAI } from './aiDecision.js'
export type { AiDecision } from './aiDecision.js'
export { readScallopConfig, readAiConfig, readWalrusConfig } from './config.js'
export type { WalrusUploader, WalrusClientConfig } from './walrus.js'
export { WalrusUploaderImpl } from './walrus.js'
