import { SuiJsonRpcClient, getJsonRpcFullnodeUrl } from '@mysten/sui/jsonRpc'
import type { Ed25519Keypair } from '@mysten/sui/keypairs/ed25519'
import type Anthropic from '@anthropic-ai/sdk'
import { fetchPolicyState, validateAction, buildActionPtb } from 'actionflow'
import type { ScallopConfig } from 'actionflow'
import { loadAgentKeypair, submitTransaction } from 'agentrunner'
import type { RunActionResult } from 'agentrunner'
import { checkEligibility } from './decision.js'
import { consultDecisionAI } from './aiDecision.js'

export interface PolicyLoopOptions {
  policyId: string
  packageId: string
  walrusBlobId: string
  scallop?: ScallopConfig
  suiClient?: SuiJsonRpcClient
  signer?: Ed25519Keypair
  ai?: {
    client: Anthropic
    marketContext?: string
    throwOnAiFailure?: boolean
  }
}

export type PolicyLoopResult =
  | { ok: true; status: 'skipped'; reason: string }
  | RunActionResult

export async function runPolicyCycle(opts: PolicyLoopOptions): Promise<PolicyLoopResult> {
  const suiClient =
    opts.suiClient ?? new SuiJsonRpcClient({ url: getJsonRpcFullnodeUrl('testnet'), network: 'testnet' })
  const nowMs = Date.now()

  const state = await fetchPolicyState(opts.policyId, suiClient)

  const eligibility = checkEligibility(state, nowMs)
  if (!eligibility.eligible) {
    return { ok: true, status: 'skipped', reason: eligibility.reason }
  }

  let decision: { protocol: string; amount: number; action: 'supply' }

  if (opts.ai) {
    const aiDecision = await consultDecisionAI(state, opts.ai.client, {
      marketContext: opts.ai.marketContext,
      throwOnAiFailure: opts.ai.throwOnAiFailure,
    })
    if (aiDecision.kind === 'skip') {
      return { ok: true, status: 'skipped', reason: aiDecision.reason }
    }
    // action: 'supply' added here — not generated by Claude — so Claude cannot
    // accidentally emit an unsupported action type.
    decision = { protocol: aiDecision.protocol, amount: aiDecision.amount, action: 'supply' }
  } else {
    // Legacy mode: maintained solely for backward compatibility with existing callers
    // that have not configured an AI client. It is NOT used as a fallback after AI
    // failures — if opts.ai is provided but Claude fails, the cycle skips.
    decision = {
      protocol: state.allowedProtocols[0],
      amount: Math.min(state.maxTotalBudget - state.spentTotal, state.maxSingleTx),
      action: 'supply',
    }
  }

  const validated = validateAction(
    { protocol: decision.protocol, amount: decision.amount, action: decision.action },
    state,
    nowMs,
    opts.policyId,
  )
  if (!validated.ok) {
    return { ok: false, status: 'validation_failed', errors: validated.errors }
  }

  const built = buildActionPtb(validated.action, opts.walrusBlobId, opts.packageId, opts.scallop)
  if (!built.ok) {
    return built
  }

  const signer = opts.signer ?? loadAgentKeypair()
  built.tx.setSender(signer.toSuiAddress())

  return submitTransaction(built.tx, signer, suiClient)
}

export { checkEligibility } from './decision.js'
export type { EligibilityResult } from './decision.js'
export { consultDecisionAI } from './aiDecision.js'
export type { AiDecision } from './aiDecision.js'
