[package]
name = "nexus_agent_wallet"
edition = "2024.beta"

[dependencies]
protocol = { git = "https://github.com/scallop-io/sui-lending-protocol.git", subdir = "contracts/protocol", rev = "2425b5b8b107bda10f4fa04517eb3cc009817249" }

[addresses]
nexus_agent_wallet = "0x0"
